### ISSUE TITLE
Lab - Pre Install 

### ISSUE THREAD

**Issue by rahulsarda1** [rahulsarda1/SEBC#1]
Updated the documentation for Pre Install

**Comment by mfernest** [comment]
It looks like you plan to create an Issue for each lab exercise -- please don't do this. Refer to #4 for further instructions.

**Comment by rahulsarda1** [comment]
Completed following
- AWS EC2 Setup
- Pre Install Steps
- MariaDB replication
- Cloudera Manager setup with 3 Zoopkeeper instances
