### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by rahulsarda1** [rahulsarda1/SEBC#5]

**Comment by rahulsarda1** [comment]
Facing Issues in Storage
Started Pre_Install.md
replica_working.md - Issue Maria DB replication
Oozie Issues uploaded cm_installed.png
Reinstalled 4 times and finally completed

**Comment by rahulsarda1** [comment]
Completed Pre_Install.md
Completed replica_working.md - Issue Maria DB replication
Completed and uploaded cm_installed.png

**Comment by rahulsarda1** [comment]
@Please review

**Comment by mfernest** [comment]
* You have some great notes for your pre-install work. Notice however you did not demonstrate a reverse lookup (IP -> FQDN).
* The disadvantage to installing a JDK yourself, as you might have experienced, is that Cloudera Manager may not detect. There are a couple ways to solve this: one is to use the `alternatives(1)` command to make your installed JDK the system default.
* You went a little overboard in the `1_preinstall.md` file, which is fine for your own notes. To keep my own work efficient, however, I ignore any extras you happen to throw in.

**Comment by mfernest** [comment]
In `2_replica_working.md` your slave status doesn't report the value that shows replication is working. Please review the lab notes for the expected result.
