### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by rahulsarda1** [rahulsarda1/SEBC#6]

**Comment by rahulsarda1** [comment]
Pending Replication to another cluster 
Started other labs

**Comment by rahulsarda1** [comment]
Pending Replicate to another cluster
Completed Test HDFS throughput- teregen and Terasort
Completed - Test HDFS Snapshots
Completed - Enable HDFS HA

**Comment by rahulsarda1** [comment]
@Please review

**Comment by mfernest** [comment]
* Replication lab not submitted
* teragen/terasort looks good
* Command-line snapshot exercise is missing some steps
* HDFS HA and CM User labs complete
