### ISSUE TITLE
YARN/RM Lab

### ISSUE THREAD

**Issue by rahulsarda1** [rahulsarda1/SEBC#7]

**Comment by rahulsarda1** [comment]
Completed YARN/RM Lab: Static Service Pools

**Comment by rahulsarda1** [comment]
Completed  YARN/RM Lab: Review the Tuning Guides

**Comment by rahulsarda1** [comment]
Completed YARN/RM Lab: Tuning for YARN

**Comment by mfernest** [comment]
* It looks like your `YARNtest.sh` only varies on heap size for duration tests. Since you only test one run-time configuration (8 mappers, 1 reducer), you won't determine if a different set of parameters can give you a shorter or longer job duration.
