### ISSUE TITLE
Securities Lab

### ISSUE THREAD

**Issue by rahulsarda1** [rahulsarda1/SEBC#9]

**Comment by rahulsarda1** [comment]
Enabled Kerberos and updated files
security/labs/kadm5.acl
security/labs/kdc.conf
security/labs/kinit.md
security/labs/krb5.conf

**Comment by rahulsarda1** [comment]
Completed Sentry Lab

**Comment by mfernest** [comment]
`[domain_realm]` stanza in `/etc/krb5.conf` is not valid.
